[package]
name = "asset"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-crypto-primitives = { version = "0.4.0", features = ["signature"] }
ark-ec = "0.4"
ark-ff = "0.4"
ark-secp256k1 = "0.4"
ark-bls12-381 = "0.4"
ark-serialize = "0.4"
ark-std = "0.4"
digest = "0.10"
sha3 = "0.10"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "benchmark"
harness = false

[[bench]]
name = "benchmark_scaling"
harness = false